apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: frontend
      color: green
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: frontend
        service: frontend
        color: green
        language: javascript
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: majunga.azurecr.io/frontend:2
        ports:
        - containerPort: "#[frontPorts]#"
          name: frontend
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: "#[frontPorts]#"
  selector:
    type: frontend
    service: frontend
    color: green

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: backend
      color: blue
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: backend
        service: backend
        color: blue
        language: csharp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: backend
        image: majunga.azurecr.io/backend:3
        env:
        - name: ASPNETCORE_URLS
          value: '#[URL]#'
        - name: MicrosoftAppId
          value: '#[msAppId]#'
        - name: MicrosoftAppPassword
          value: '#[msAppPass]#'
        - name: ASPNETCORE_ENVIRONMENT
          value: '#[env]#'
        ports:
        - containerPort: 3978
          name: backend
        readinessProbe:
          httpGet:
            path: /static/test.txt
            port: 3978
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /static/test.txt
            port: "#[backendPorts]#"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
  - port: "#[backendPorts]#"
  selector:
    type: backend
    service: backend
    color: blue
